export default get_meta_data_color = [
    {
        name: 'Cyan',
        book: '',
        id: 'Cyan',
        type: 'standard',
        is_process: true,
        opacity: 0,
        press: 'Digital',
        custominfo: 'Info for Cyan',
        red: 0,
        green: 0.682353,
        blue: 0.937255,
        cyan: 1,
        magenta: 0,
        yellow: 0,
        black: 0,
        L: 62,
        a: -44,
        b: -50,
        Loriginal: 62,
        index: 0,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'Magenta',
        book: '',
        id: 'Magenta',
        type: 'standard',
        is_process: true,
        opacity: 0,
        press: 'Digital',
        custominfo: 'Info for Magenta',
        red: 0.92549,
        green: 0,
        blue: 0.54902,
        cyan: 0,
        magenta: 1,
        yellow: 0,
        black: 0,
        L: 52,
        a: 81,
        b: -7,
        Loriginal: 52,
        index: 1,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'Yellow',
        book: '',
        id: 'Yellow',
        type: 'standard',
        is_process: true,
        opacity: 0,
        press: 'Digital',
        custominfo: 'Info for Yellow',
        red: 1,
        green: 0.94902,
        blue: 0,
        cyan: 0,
        magenta: 0,
        yellow: 1,
        black: 0,
        L: 95,
        a: -6,
        b: 95,
        Loriginal: 95,
        index: 2,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'Black',
        book: '',
        id: 'Black',
        type: 'standard',
        is_process: true,
        opacity: 0,
        press: 'Digital',
        custominfo: 'Info for Black',
        red: 0.137255,
        green: 0.121569,
        blue: 0.12549,
        cyan: 0,
        magenta: 0,
        yellow: 0,
        black: 1,
        L: -100,
        a: 2,
        b: 0,
        Loriginal: 12,
        index: 3,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'PANTONE 360 C',
        book: 'PANTONE® Solid Coated V5 M0 D50 2°',
        id: 'PANTONE__360__C',
        type: 'standard',
        is_process: false,
        opacity: 0,
        press: 'flexo',
        custominfo: 'Info for P360 C',
        red: 0.54,
        green: 0.76,
        blue: 0.35,
        cyan: 0.59,
        magenta: 0,
        yellow: 0.9,
        black: 0,
        L: 70.730003,
        a: -43.41,
        b: 47.099998,
        Loriginal: 70.730003,
        index: 4,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'PANTONE 485 C',
        book: 'PANTONE® Solid Coated V5 M0 D50 2°',
        id: 'PANTONE__485__C',
        type: 'standard',
        is_process: false,
        opacity: 0,
        press: 'flexo',
        custominfo: 'Info for P485 C',
        red: 0.73,
        green: 0.18,
        blue: 0.14,
        cyan: 0,
        magenta: 0.95,
        yellow: 1,
        black: 0,
        L: 49.880001,
        a: 69.059998,
        b: 53.869999,
        Loriginal: 49.880001,
        index: 5,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'PANTONE 7548 C',
        book: 'PANTONE® Solid Coated V5 M0 D50 2°',
        id: 'PANTONE__7548__C',
        type: 'standard',
        is_process: false,
        opacity: 0,
        press: 'flexo',
        custominfo: 'Info for P7548 C',
        red: 0.96,
        green: 0.77,
        blue: 0,
        cyan: 0,
        magenta: 0.11,
        yellow: 1,
        black: 0,
        L: 83.980003,
        a: 13.07,
        b: 103.599998,
        Loriginal: 83.980003,
        index: 6,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'PANTONE Pink C',
        book: 'PANTONE® Solid Coated V5 M0 D50 2°',
        id: 'PANTONE__Pink__C',
        type: 'standard',
        is_process: false,
        opacity: 0,
        press: 'flexo',
        custominfo: 'Info for Pink C',
        red: 0.72,
        green: 0.16,
        blue: 0.61,
        cyan: 0.09,
        magenta: 0.89,
        yellow: 0,
        black: 0,
        L: 51.25,
        a: 73.389999,
        b: -19.23,
        Loriginal: 51.25,
        index: 7,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'White 1',
        book: '',
        id: 'White__1',
        type: 'standard',
        is_process: false,
        opacity: 0,
        press: 'offset',
        custominfo: 'Info for White 1',
        red: 0.949,
        green: 0.941,
        blue: 0.69,
        cyan: 0.02,
        magenta: 0,
        yellow: 0.45,
        black: 0,
        L: 93.900002,
        a: -6.28,
        b: 31.280001,
        Loriginal: 93.900002,
        index: 8,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'White 2',
        book: '',
        id: 'White__2',
        type: 'standard',
        is_process: false,
        opacity: 0,
        press: 'offset',
        custominfo: 'Info for White 2',
        red: 0.631,
        green: 0.89,
        blue: 0.788,
        cyan: 0.41,
        magenta: 0,
        yellow: 0.31,
        black: 0,
        L: 82.940002,
        a: -37.060001,
        b: 0.73,
        Loriginal: 82.940002,
        index: 9,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'Varnish 1',
        book: '',
        id: 'Varnish__1',
        type: 'varnish',
        is_process: false,
        opacity: 0,
        press: 'offset',
        custominfo: 'Info for Varnish 1',
        red: 0.529,
        green: 0.69,
        blue: 0.729,
        cyan: 0.56,
        magenta: 0.08,
        yellow: 0.21,
        black: 0.02,
        L: 67.709999,
        a: -19.09,
        b: -13.71,
        Loriginal: 67.709999,
        index: 10,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'Varnish 2',
        book: '',
        id: 'Varnish__2',
        type: 'varnish',
        is_process: false,
        opacity: 0,
        press: 'offset',
        custominfo: 'Info for Varnish 2',
        red: 0.878,
        green: 0.69,
        blue: 0.922,
        cyan: 0,
        magenta: 0.34,
        yellow: 0,
        black: 0,
        L: 80.589996,
        a: 30.84,
        b: -18.93,
        Loriginal: 80.589996,
        index: 11,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'Gold',
        book: '',
        id: 'Gold',
        type: 'standard',
        is_process: false,
        opacity: 1,
        press: 'screen',
        custominfo: 'Info for Gold',
        red: 0.502,
        green: 0.412,
        blue: 0.231,
        cyan: 0.355,
        magenta: 0.478,
        yellow: 0.888,
        black: 0.344,
        L: 46.939999,
        a: 7.23,
        b: 34.23,
        Loriginal: 46.939999,
        index: 12,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'Silver',
        book: '',
        id: 'Silver',
        type: 'standard',
        is_process: false,
        opacity: 1,
        press: 'screen',
        custominfo: 'Info for Silver',
        red: 0.651,
        green: 0.651,
        blue: 0.659,
        cyan: 0.377,
        magenta: 0.282,
        yellow: 0.284,
        black: 0.071,
        L: 68.889999,
        a: -0.77,
        b: -1.23,
        Loriginal: 68.889999,
        index: 13,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'Diecut',
        book: '',
        id: 'Diecut',
        type: 'technical',
        is_process: false,
        opacity: 0,
        press: 'other',
        custominfo: 'Info for Diecut',
        red: 0.69,
        green: 0,
        blue: 0.361,
        cyan: 0,
        magenta: 1,
        yellow: 0.24,
        black: 0.04,
        L: 44.040001,
        a: 79.400002,
        b: 8.49,
        Loriginal: 44.040001,
        index: 14,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'Dimensions',
        book: '',
        id: 'Dimensions',
        type: 'technical',
        is_process: false,
        opacity: 0,
        press: 'other',
        custominfo: 'Info for Dimensions',
        red: 0,
        green: 0.671,
        blue: 0.522,
        cyan: 0.93,
        magenta: 0,
        yellow: 0.63,
        black: 0,
        L: 57.740002,
        a: -77.160004,
        b: 0.18,
        Loriginal: 57.740002,
        index: 15,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
];
