const packz_data = [
    {
        name: 'Airwaves_Blau',
        book: '',
        id: 'Airwaves_5FBlau',
        type: 'standard',
        is_process: false,
        opacity: 0,
        press: 'unknown',
        custominfo: '',
        red: 0.0078,
        green: 0.129,
        blue: 0.424,
        cyan: 1,
        magenta: 0.85,
        yellow: 0,
        black: 0.39,
        L: -100,
        a: 16.290001,
        b: -47.560001,
        Loriginal: 15.38,
        index: 0,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'Airwaves_Gruen',
        book: '',
        id: 'Airwaves_5FGruen',
        type: 'standard',
        is_process: false,
        opacity: 0,
        press: 'unknown',
        custominfo: '',
        red: 0,
        green: 0.694,
        blue: 0.557,
        cyan: 0.79,
        magenta: 0,
        yellow: 0.6,
        black: 0,
        L: 63.400002,
        a: -53.279999,
        b: 5.55,
        Loriginal: 63.400002,
        index: 1,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'PANTONE 485 C',
        book: 'PANTONE® Solid Coated V5 M0 D50 2°',
        id: 'PANTONE__485__C',
        type: 'standard',
        is_process: false,
        opacity: 0,
        press: 'unknown',
        custominfo: '',
        red: 0.73,
        green: 0.18,
        blue: 0.14,
        cyan: 0,
        magenta: 0.95,
        yellow: 1,
        black: 0,
        L: 49.880001,
        a: 69.059998,
        b: 53.869999,
        Loriginal: 49.880001,
        index: 2,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'P2955C',
        book: '',
        id: 'P2955C',
        type: 'standard',
        is_process: false,
        opacity: 0,
        press: 'unknown',
        custominfo: '',
        red: 0,
        green: 0.216,
        blue: 0.404,
        cyan: 1,
        magenta: 0.52,
        yellow: 0,
        black: 0.58,
        L: 20.709999,
        a: -7.34,
        b: -35.349998,
        Loriginal: 20.709999,
        index: 3,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'Lack',
        book: '',
        id: 'Lack',
        type: 'varnish',
        is_process: false,
        opacity: 0,
        press: 'unknown',
        custominfo: '',
        red: 0.855,
        green: 0.855,
        blue: 0.855,
        cyan: 0,
        magenta: 0,
        yellow: 0,
        black: 0.2,
        L: 87,
        a: 0.51,
        b: 0.59,
        Loriginal: 87,
        index: 4,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'Schnitt',
        book: '',
        id: 'Schnitt',
        type: 'technical',
        is_process: false,
        opacity: 0,
        press: 'unknown',
        custominfo: '',
        red: 0.902,
        green: 0,
        blue: 0.494,
        cyan: 0,
        magenta: 1,
        yellow: 0,
        black: 0,
        L: 49.700001,
        a: 80.800003,
        b: -1.5,
        Loriginal: 49.700001,
        index: 5,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'Bemassung',
        book: '',
        id: 'Bemassung',
        type: 'technical',
        is_process: false,
        opacity: 0,
        press: 'unknown',
        custominfo: '',
        red: 0,
        green: 0.592,
        blue: 0.855,
        cyan: 1,
        magenta: 0,
        yellow: 0,
        black: 0,
        L: 54.993519,
        a: -36.980469,
        b: -49.984379,
        Loriginal: 54.993519,
        index: 6,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
    {
        name: 'Schnitt_GF',
        book: '',
        id: 'Schnitt_5FGF',
        type: 'technical',
        is_process: false,
        opacity: 0,
        press: 'unknown',
        custominfo: '',
        red: 0,
        green: 0.624,
        blue: 0.89,
        cyan: 1,
        magenta: 0,
        yellow: 0,
        black: 0,
        L: 57.299999,
        a: -39.900002,
        b: -51.200001,
        Loriginal: 57.299999,
        index: 7,
        subindex: 0,
        enabled: true,
        usage: 'Used',
    },
];

export function getDarkestColor(colors) {
    return colors.reduce((darkest, current) => {
        if (!darkest || current.L < darkest.L) {
            return current;
        }
        return darkest;
    }, null)?.name;
}
